// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsiaPropertyTransaction.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MsiaPropertyTransaction.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260117152337_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MsiaPropertyTransaction.Models.PropertyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("district");

                    b.Property<decimal?>("LandParcelArea")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("land_parcel_area");

                    b.Property<decimal>("MainFloorArea")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("main_floor_area");

                    b.Property<string>("Mukim")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mukim");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property_type");

                    b.Property<string>("PropertyTypeStrata")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property_type_strata");

                    b.Property<string>("RoadName")
                        .HasColumnType("text")
                        .HasColumnName("road_name");

                    b.Property<string>("SchemeNameArea")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scheme_name_area");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sector");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Tenure")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenure");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<decimal>("TransactionPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("transaction_price");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<string>("UnitLevel")
                        .HasColumnType("text")
                        .HasColumnName("unit_level");

                    b.HasKey("Id");

                    b.ToTable("property_transactions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
